### ISSUE TITLE
Crash on load if both Thaumcraft and JEI are installed.

### ISSUE THREAD

**Issue by talonos2** [CleanroomMC/Modular-Magic#5]
I tried to get the minimum possible modpack to repro this issue: Mixin Booter, Baubles, CraftTweaker, JEI, Modular Machinery Community Edition, Thaumcraft, and Modular Magic.

For version numbers for all these mods, see the crash report.

If you remove Thaumcraft, this crash does not occur. If you remove JEI, this crash does not occur. If you remove Modular Magic, this crash does not occur.

Help requested. I really would like to use Modular Magic in my pack!

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-9.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 5/18/24 9:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: class thaumcraft.api.aspects.AspectList=mezz.jei.startup.ModIngredientRegistration$$Lambda$279/2142435076@57aecbd9 and class thaumcraft.api.aspects.AspectList=mezz.jei.startup.ModIngredientRegistration$$Lambda$279/2142435076@53e86b98
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at mezz.jei.ingredients.IngredientRegistry.<init>(IngredientRegistry.java:66)
	at mezz.jei.startup.ModIngredientRegistration.createIngredientRegistry(ModIngredientRegistration.java:55)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:62)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

No Mixin Metadata is found in the Stacktrace.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1414366128 bytes (1348 MB) / 1866465280 bytes (1780 MB) up to 7605846016 bytes (7253 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8160m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version      | Source                                    | Signature                                |
	|:------ |:---------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp              | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mixinbooter      | 9.1          | minecraft.jar                             | None                                     |
	| LCHIJA | baubles          | 1.5.2        | Baubles-1.12-1.5.2.jar                    | None                                     |
	| LCHIJA | crafttweaker     | 4.1.20       | CraftTweaker2-1.12-4.1.20.698.jar         | None                                     |
	| LCHIJA | ctgui            | 1.0.0        | CraftTweaker2-1.12-4.1.20.698.jar         | None                                     |
	| LCHIJE | jei              | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                 | None                                     |
	| LCHIJ  | crafttweakerjei  | 2.0.3        | CraftTweaker2-1.12-4.1.20.698.jar         | None                                     |
	| LCHIJ  | modularmachinery | 1.11.1       | ModularMachinery-CE-1.12.2-1.11.1-r55.jar | None                                     |
	| LCHIJ  | thaumcraft       | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar          | None                                     |
	| LCHIJ  | modularmagic     | 1.6.1        | modularmagic-1.7.0+forked.jar             | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-9.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.23' Renderer: 'NVIDIA GeForce RTX 3090/PCIe/SSE2'```

**Comment by talonos2** [comment]
Found it.

The crash was saying that thaumcraft.api.aspects.AspectList was getting registered multiple times, and so I looked through your code to find out where you were registering thaumcraft.api.aspects.AspectList and found the following.

https://github.com/Rongmario/Modular-Magic/blob/10a1088cdca36de94f475fd7518ac0e64f132acc/src/main/java/fr/frinn/modularmagic/common/integration/JeiPlugin.java#L31C3-L33C10

It seems as though if Thaumic JEI is *not* present, you register thaumcraft.api.aspects.AspectList to JEI, causing the crash.

Adding Thaumic JEI fixes the crash by making Modular Magic skip this registration.

Should probably be fixed, but if anybody else runs into this issue and found their way here, that's how you solve it.
